"""add blocked_ips table

Revision ID: 47c18d6a3e86
Revises: 70a159675920
Create Date: 2026-07-28 14:55:27.917033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c18d6a3e86'
down_revision = '70a159675920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('blocked_by', sa.String(length=10), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocked_ips_ip'), ['ip'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blocked_ips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocked_ips_ip'))

    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
