"""add login_attempts table

Revision ID: 70a159675920
Revises: tz_aware_datetime
Create Date: 2026-07-27 14:15:26.027647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a159675920'
down_revision = 'tz_aware_datetime'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)
        batch_op.create_index('ix_login_attempts_ip_timestamp', ['ip', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_timestamp'))
        batch_op.drop_index('ix_login_attempts_ip_timestamp')
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
